### ISSUE TITLE
Add the visualizer to CI (and fix regressions)

### ISSUE THREAD

**Issue by bocchino** [nasa/fprime#3939]
Because the visualizer is not in CI, there is a danger of regression. We have already seen this with the subtopology work: https://github.com/nasa/fprime/issues/3868. The same thing can happen with respect to the XML tools: https://github.com/nasa/fprime/issues/3938.

**Comment by bocchino** [comment]
Also, I suspect a regression may have happened already. When I run the visualizer in `Ref/Top`, I get this:
```
Built target refresh_cache
[ERROR] Context must be a Path
```
Possibly I am doing something wrong, but this looks like anomalous behavior.

**Comment by thomas-bc** [comment]
Still needed: add to CI

**Comment by thomas-bc** [comment]
Done: fixed regression

**Comment by bocchino** [comment]
@thomas-bc I'm still seeing the `Context must be a path` error. I'm on this commit of nasa/fprime: bf7d9866cff010dbdbeaf6bb999542ad2c227169. I did a fresh install of F Prime with the requirements listed in this branch.

**Comment by thomas-bc** [comment]
Yes the `fprime-tools` release hasn't hit `fprime@devel` yet. Figuring out CI on https://github.com/nasa/fprime/pull/3961/

**Comment by thomas-bc** [comment]
`pip install fprime-tools==4.0.0a8` should fix it

**Comment by bocchino** [comment]
Got it, thanks!
