### ISSUE TITLE
ComQueue Unit Test testQueueSend reading from deallocated stack variable

### ISSUE THREAD

**Issue by dskin344** [nasa/fprime#4305]
In attempt to make sure the pre-written ComQueue unit tests run before adding my own, I came across an AddressSanitizer Stack-After-Use-Scope error from emittedBuffer.getData()[i] in the following call stack:

TEST(Nominal, Send)
tesQueueSend()
emitOneAndCheck
ASSERT_EQ(emittedBuffer.getData()[i], expectedData[i]);

The reference to the pointer emittedBuffer.getData[i] triggers this issue, from what I found (based on preliminary research) is due to the pointer stored in emittedBuffer is returned from processQueue() in ComQueue.cpp when sendComBuffer passes the pointer to the stack allocated buffer flows downstream through the dataOut port, and captured by the test harness history. Then when referencing the index of the buffer address stored in the pointer, the Stack-After-Use-Scope error is triggered. 

I came across this when implementing additional functionality in a copy of the ComQueue component (that I had moved to my Components folder), and so while I do not think this is due to my additional changes, I wanted it to be know when this is investigated by others. I also ran into the same issue on the unchanged ComQueue Component in Svc folder, hence my premonition that this issue should occur on other machines/implementations as well.

Is this issue something on my end? Do you see this problem as well? Thank you.

**Comment by thomas-bc** [comment]
Thanks for reporting!
It sounds like you may be talking about the issue that was fixed here: https://github.com/nasa/fprime/pull/4190/files#diff-ad8436a155e0dfa4cd546b2a2d8506e685c28249fcf2aa05412b58874c34d753
Can you confirm? Are you using the v4.0.0 tag? If you are, you can check if that fixes it by checking out `devel` and running the address sanitizer there.

**Comment by thomas-bc** [comment]
Now this does raise the question of why hasn't this tripped up CI, I thought sanitizers would... I will need to investigate.

**Comment by bocchino** [comment]
@thomas-bc I think the code is still buggy. I think the root cause of this bug is here, specifically the `ref` annotation in the first argument:

https://github.com/nasa/fprime/blob/2ee27f82f3d3539a44e92995ea41da3cd18f38ea/Svc/Ports/CommsPorts/CommsPorts.fpp#L17

We should avoid passing `Fw::Buffer` objects by reference through ports, except when the receiver has to modify the `Fw::Buffer` object seen by the invoking component, e.g., to do memory allocation. `Fw::Buffer` objects themselves are references (they store pointers) but they are small objects that should be passed by value if the intent is to pass the data to another component.

**Comment by bocchino** [comment]
On further investigation, the `ref` specifier is probably not causing the behavior described, since the invalid address is the address of the data pointed to by the buffer, not the address of the buffer itself. So maybe this is the issue reported in #4190? I still think we should pass buffers by value and not by reference, unless the intent is to modify the buffer held by the caller.

**Comment by dskin344** [comment]
Yesterday checking I was on fprime version 4.0.0, after looking at the linked issue, I checked out to devel in my local fprime repo, and ran the same unit tests for Svc/ComQueue where I ran into the same address sanitizer error:

_Checkout to Devel_
git checkout devel
Previous HEAD position was abb09e4a6 Bump Tools and GDS (#4000)
Switched to branch 'devel'
Your branch is up to date with 'origin/devel'.

_Printed error_
19: [ RUN      ] Nominal.Send
19: =================================================================
19: ==2699086==ERROR: AddressSanitizer: stack-use-after-return on address 0x76bf91a03cf8 at pc 0x6253b08feb8a bp 0x7ffe90aa52f0 sp 0x7ffe90aa52e0
19: READ of size 1 at 0x76bf91a03cf8 thread T0
19:     #0 0x6253b08feb89 in testing::AssertionResult testing::internal::CmpHelperEQ<unsigned char, unsigned char>(char const*, char const*, unsigned char const&, unsigned char const&) (/home/derek/EnosMk1/flight-software/lib/fprime/build-fprime-automatic-native-ut/bin/Linux/Svc_ComQueue_ut_exe+0x578b89) (BuildId: 623d19ce4c9eae090f3c7782f0342708e7e47fcc)
19:     #1 0x6253b08fb6fd in testing::AssertionResult testing::internal::EqHelper::Compare<unsigned char, unsigned char, (void*)0>(char const*, char const*, unsigned char const&, unsigned char const&) (/home/derek/EnosMk1/flight-software/lib/fprime/build-fprime-automatic-native-ut/bin/Linux/Svc_ComQueue_ut_exe+0x5756fd) (BuildId: 623d19ce4c9eae090f3c7782f0342708e7e47fcc)
19:     #2 0x6253b08cfded in Svc::ComQueueTester::emitOneAndCheck(short, unsigned char*, unsigned long) /home/derek/EnosMk1/flight-software/lib/fprime/Svc/ComQueue/test/ut/ComQueueTester.cpp:72
19:     #3 0x6253b08d0f9e in Svc::ComQueueTester::testQueueSend() /home/derek/EnosMk1/flight-software/lib/fprime/Svc/ComQueue/test/ut/ComQueueTester.cpp:88
19:     #4 0x6253b08bffe2 in Nominal_Send_Test::TestBody() /home/derek/EnosMk1/flight-software/lib/fprime/Svc/ComQueue/test/ut/ComQueueTestMain.cpp:9

Not sure if this is still an issue unique to me, or a larger scale one, but as far as I know I have not changed anything.

**Comment by bocchino** [comment]
The issue could be in the unit test code. This code looks suspicious:

https://github.com/nasa/fprime/blob/2fca863e4dea1efa9b8744e2244caa1f97770960/Svc/ComQueue/test/ut/ComQueueTester.cpp#L80-L100

It is allocating a `ComBuffer` on the stack, creating a `Buffer` that points to it, and sending the buffer out on a port.

**Comment by dskin344** [comment]
Well, this issue might actually be resolved, I was mistakenly not on the most updated version of devel, after fetching, and updating my tool, all unit tests for Svc/ComQueue passed, so it seems that the the fix 4290 mentioned above is the resolution to this bug.

**Comment by thomas-bc** [comment]
Closing as it seems resolved.
